server:
  port: 8180

spring:
  application:
    name: dubbo-provider

  #database config
  datasource:
    url: jdbc:mysql://localhost:3306/learn
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #kafka server config
  kafka:
    bootstrap-servers: 127.0.0.1:9092

# mybatis config
mybatis:
  mapper-locations: classpath:mapper/*.xml

# dubbo config
dubbo:
  registry:
    address: nacos://127.0.0.1:8848 # registry addr
  application:
    name: dubbo-provider # appname
  protocol:
    name: dubbo #dubbo protocol
    port: 20880
  scan:
    base-packages: com.service.pointservice
  provider:
    timeout: 30000