server:
  port: 8181

spring:
  application:
    name: dubbo-consumer

  #database config
  datasource:
    url: jdbc:mysql://localhost:3306/learn
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  #kafka server config
  kafka:
    bootstrap-servers: 127.0.0.1:9092

  # redis config
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 5000
    jedis:
      pool:
        max-active: 8
        max-wait: 1
        max-idle: 8
        min-idle: 0

# dubbo config
dubbo:
  registry:
    address: nacos://127.0.0.1:8848
  application:
    name: dubbo-consumer
  consumer:
    timeout: 30000

# alipay config
alipay:
  easy:
    protocol: https
    gatewayHost: openapi-sandbox.dl.alipaydev.com
    signType: RSA2
    # todo config by yourself
    appId: app_id
    merchantPrivateKey: application_private_key
    alipayPublicKey: alipay_public_key
    # callback url in your service
    notifyUrl: url_by_nat_traversal_tool/notify